<?php
// $localidadesBuenosAires = [
//     "Acassuso",
//     "Adrogué",
//     "Alejandro Korn",
//     "Avellaneda",
//     "Azul",
//     "Bahía Blanca",
//     "Balcarce",
//     "Banfield",
//     "Beccar",
//     "Bella Vista",
//     "Benavídez",
//     "Berazategui",
//     "Berisso",
//     "Bernal",
//     "Bolívar",
//     "Boulogne",
//     "Bragado",
//     "Burzaco",
//     "Campana",
//     "Cañuelas",
//     "Carlos Casares",
//     "Caseros",
//     "Castelar",
//     "Chascomús",
//     "Chivilcoy",
//     "Ciudadela",
//     "Claypole",
//     "Del Viso",
//     "Dock Sud",
//     "Don Torcuato",
//     "El Jagüel",
//     "El Palomar",
//     "Ensenada",
//     "Escobar",
//     "Esteban Echeverría",
//     "Ezeiza",
//     "Ezpeleta",
//     "Florencio Varela",
//     "Florida",
//     "General Pacheco",
//     "General Rodríguez",
//     "Gerli",
//     "Glew",
//     "Grand Bourg",
//     "Haedo",
//     "Hudson",
//     "Hurlingham",
//     "Ingeniero Maschwitz",
//     "Ituzaingó",
//     "José C. Paz",
//     "Junín",
//     "La Plata",
//     "Lanús",
//     "Llavallol",
//     "Lomas de Zamora",
//     "Luján",
//     "Malvinas Argentinas",
//     "Manuel Alberti",
//     "Mar de Ajó",
//     "Mar del Plata",
//     "Marcos Paz",
//     "Martínez",
//     "Mercedes",
//     "Merlo",
//     "Miramar",
//     "Monte Grande",
//     "Moreno",
//     "Morón",
//     "Munro",
//     "Necochea",
//     "Nueve de Julio",
//     "Olavarría",
//     "Olivos",
//     "Pergamino",
//     "Pilar",
//     "Pinamar",
//     "Quilmes",
//     "Rafael Calzada",
//     "Ramos Mejía",
//     "Remedios de Escalada",
//     "San Andrés",
//     "San Antonio de Padua",
//     "San Clemente del Tuyú",
//     "San Fernando",
//     "San Francisco Solano",
//     "San Isidro",
//     "San Justo",
//     "San Martín",
//     "San Miguel",
//     "San Miguel del Monte",
//     "San Nicolás",
//     "San Pedro",
//     "San Vicente",
//     "Santos Lugares",
//     "Tandil",
//     "Temperley",
//     "Tigre",
//     "Tortuguitas",
//     "Trenque Lauquen",
//     "Tres Arroyos",
//     "Turdera",
//     "Valentín Alsina",
//     "Vicente López",
//     "Victoria",
//     "Villa Ballester",
//     "Villa Bosch",
//     "Villa Gesell",
//     "Villa Tesei",
//     "Virreyes",
//     "Wilde"
//   ];
// foreach($localidadesBuenosAires as $localidad){
// $conexion=mysqli_connect("localhost","root","","base_proyecto_wed");
// $consulta="insert into localidades (localidad)values('$localidad')";
// mysqli_query($conexion,$consulta);
// }
//codigo para cargar todas las localidades
$conexion=mysqli_connect("localhost","root","","base_proyecto_wed");
$dato_recibido=file_get_contents("php://input");
if($dato_recibido=="leer_localidades"){
    $consulta="select * from localidades";
    $respuesta=mysqli_query($conexion,$consulta);
    $array_localidades=[];
    while($fila=mysqli_fetch_array($respuesta)){
        $array_localidades[]=$fila["localidad"];
    }
    header("Content-Type: application/json");
    echo(json_encode($array_localidades));
}
?>